name: Build-OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  
  push:
  
  schedule:
    - cron: 0 17 * * *

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CHOOSE_VERSION: origin/master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  DIY_P3_SH: diy-part3.sh
  SCKEY: ${{ secrets.SCKEY }}
  GH_TOKEN: ${{ github.token }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} 
  FREE_UP_DISK: true
  UPLOAD_FILES: false
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: WeChat notification
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=开始编译OpenWrt"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=开始编译OpenWrt
          
      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /var/cache/apt/archives /usr/local/share/boost /usr/local/go* /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox* google* dotnet* openjdk* mysql* php* android* mongodb* moby* snapd* libreoffice* gnome* unity-webapps-common lxd printer* cups* foomatic* hplip* bluez* aisleriot* shotwell* rhythmbox* thunderbird* transmission* totem* cheese* \
          cloud-init cloud-guest-utils cloud-initramfs-copymods cloud-initramfs-dyn-netconf ubuntu-server landscape-common linux-cloud-tools-common linux-cloud-tools-generic linux-firmware linux-tools-generic linux-modules-extra-$(uname -r) linux-headers-$(uname -r) language-pack* aspnetcore-targeting-pack*
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev libarchive-tools
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo chmod 777 /workdir
          df -hT
           
      - name: Clean Cache
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          BRANCH=master
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1,2,3 )
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR; do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
        env:
          GH_TOKEN: ${{ github.token }}
 
      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone -b $REPO_BRANCH --single-branch $REPO_URL openwrt
          ln -sf /workdir/openwrt ${{ github.workspace }}/openwrt
        
      - name: Choose openwrt version
        run: |
          cd openwrt
          git checkout $CHOOSE_VERSION
          
      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff /mnt/swapfile
          sudo rm -rf /mnt/swapfile
          sudo chmod 777 /mnt
          sudo mkdir -p -m 777 /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/build_dir/host openwrt/build_dir /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir /mnt/openwrt/build_dir /mnt/openwrt/tmp /mnt/openwrt/bin
          ln -sf /mnt/openwrt/dl openwrt/dl
          ln -sf /mnt/openwrt/tmp openwrt/tmp        
          ln -sf /mnt/openwrt/bin openwrt/bin
          # ln -sf /mnt/openwrt/build_dir/host openwrt/build_dir/host 
          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
          # ln -sf /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/hostpkg
          # ln -sf /mnt/openwrt/feeds openwrt/feeds
          ln -sf /mnt/openwrt/build_dir openwrt/build_dir
          df -hT
             
      - name: Load custom feeds
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH
        
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Load own configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
        
      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P3_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P3_SH
          # mv ${GITHUB_WORKSPACE}/patches/patches ${GITHUB_WORKSPACE}/openwrt/feeds/kenzok8/fullconenat-nft
          find "${GITHUB_WORKSPACE}/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d '${GITHUB_WORKSPACE}/openwrt' -p1 --forward"
        
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}    
        
      - name: Download package
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
      - name: Multi-thread compile
        id: Multi-thread
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1)) tools/compile
          make -j$(($(nproc) + 1)) toolchain/compile
          make -j$(($(nproc) + 1)) target/linux/compile
          make -j$(($(nproc) + 1)) package/{node,golang,php8,ruby,perl,jq,docker}/compile
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
      - name: Single-thread compile
        id: Single-thread
        if: failure() 
        run: |
          cd openwrt
          make -j1 tools/compile V=s
          make -j1 toolchain/compile V=s
          make -j1 target/linux/compile V=s
          make -j1 package/{node,golang,php8,ruby,perl,jq,docker}/compile V=s
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
       
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            /workdir/openwrt/dl
            /workdir/openwrt/tmp/
            /workdir/openwrt/bin/
            /workdir/openwrt/build_dir/host
            /workdir/openwrt/staging_dir/
            /workdir/openwrt/feeds/
            /workdir/openwrt/build_dir/hostpkg
          key: openwrt

      - name: Compress directory
        run: |
          sudo rm -rf /workdir/openwrt/dl /workdir/openwrt/tmp/ /workdir/openwrt/bin/ /workdir/openwrt/build_dir/host /workdir/openwrt/feeds/ /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf staging_dir.tar.gz /workdir/openwrt/staging_dir && sudo rm -rf /workdir/openwrt/staging_dir
          bsdtar -czlf openwrt.tar.gz /workdir/openwrt && sudo rm -rf /workdir/openwrt
          bsdtar -czlf hostpkg.tar.gz /workdir/openwrt/build_dir/hostpkg && sudo rm -rf /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf host.tar.gz /mnt/openwrt/build_dir/host && sudo rm -rf /mnt/openwrt/build_dir/host
          bsdtar -czlf bin.tar.gz /mnt/openwrt/bin && sudo rm -rf /mnt/openwrt/bin
          bsdtar -czlf dl.tar.gz /mnt/openwrt/dl && sudo rm -rf /mnt/openwrt/dl
          bsdtar -czlf feeds.tar.gz /mnt/openwrt/feeds && sudo rm -rf /mnt/openwrt/feeds
          df -hT
      
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            openwrt.tar.gz
            staging_dir.tar.gz
            hostpkg.tar.gz
            host.tar.gz
            bin.tar.gz
            dl.tar.gz
            feeds.tar.gz
          
      - name: WeChat notification
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success' && !cancelled() && job.status == 'success'
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第一部分编译成功"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第一部分编译成功
       
      - name: WeChat notification
        if: failure() && !cancelled()
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第一部分编译失败"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第一部分编译失败
      
  build1:
    needs: prepare
    runs-on: ubuntu-22.04
    steps:   
      - name: Checkout code
        uses: actions/checkout@main
             
      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /var/cache/apt/archives /usr/local/share/boost /usr/local/go* /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox* google* dotnet* openjdk* mysql* php* android* mongodb* moby* snapd* libreoffice* gnome* unity-webapps-common lxd printer* cups* foomatic* hplip* bluez* aisleriot* shotwell* rhythmbox* thunderbird* transmission* totem* cheese* \
          cloud-init cloud-guest-utils cloud-initramfs-copymods cloud-initramfs-dyn-netconf ubuntu-server landscape-common linux-cloud-tools-common linux-cloud-tools-generic linux-firmware linux-tools-generic linux-modules-extra-$(uname -r) linux-headers-$(uname -r) language-pack* aspnetcore-targeting-pack*
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev libarchive-tools
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo chmod 777 /workdir
          df -hT
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: /workdir

      - name: WeChat notification
        working-directory: /workdir
        run: |
          cd /workdir
          mkdir -p openwrt
          bsdtar -xzf openwrt.tar.gz -C /workdir/openwrt --strip-components=2 && rm openwrt.tar.gz
          ln -sf /workdir/openwrt ${{ github.workspace }}/openwrt
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt开始编译第二部分"
          rm -rf openwrt/build_dir/hostpkg openwrt/staging_dir openwrt/dl
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt开始编译第二部分
       
      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff /mnt/swapfile
          sudo rm -rf /mnt/swapfile
          sudo chmod 777 /mnt
          sudo mkdir -p -m 777 /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/build_dir/host openwrt/build_dir /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir /mnt/openwrt/build_dir /mnt/openwrt/tmp /mnt/openwrt/bin
          ln -sf /mnt/openwrt/dl openwrt/dl
          ln -sf /mnt/openwrt/tmp openwrt/tmp        
          ln -sf /mnt/openwrt/bin openwrt/bin
          # ln -sf /mnt/openwrt/build_dir/host openwrt/build_dir/host 
          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
          # ln -sf /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/hostpkg
          # ln -sf /mnt/openwrt/feeds openwrt/feeds
          ln -sf /mnt/openwrt/build_dir openwrt/build_dir
          df -hT
              
      - name: Unzip artifact
        run: |
          cd /workdir && mkdir -p openwrt/staging_dir && bsdtar -xzf staging_dir.tar.gz -C /workdir/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz       
          cd /workdir && bsdtar -xzf host.tar.gz -C /mnt/openwrt/build_dir/host --strip-components=4 && rm host.tar.gz
          cd /workdir && bsdtar -xzf bin.tar.gz -C /mnt/openwrt/bin --strip-components=3 && rm bin.tar.gz
          cd /workdir && bsdtar -xzf dl.tar.gz -C /mnt/openwrt/dl --strip-components=3 && rm dl.tar.gz
          cd /workdir && bsdtar -xzf staging_dir.tar.gz -C /mnt/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz
          cd /workdir && bsdtar -xzf feeds.tar.gz -C /mnt/openwrt/feeds --strip-components=3 && rm feeds.tar.gz
      
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
             /workdir/openwrt/dl
             /workdir/openwrt/tmp/
             /workdir/openwrt/bin/
             /workdir/openwrt/build_dir/host
             /workdir/openwrt/staging_dir/
             /workdir/openwrt/feeds/
             /workdir/openwrt/build_dir/hostpkg
          key: openwrt
          restore-keys: |
               openwrt
               
      - name: Move files
        run: |
          mv /workdir/openwrt/dl /mnt/openwrt/dl
          mv /workdir/openwrt/tmp /mnt/openwrt/tmp
          mv /workdir/openwrt/bin /mnt/openwrt/bin
          mv /workdir/openwrt/build_dir/host /mnt/openwrt/build_dir/host
          ln -sf /mnt/openwrt/dl /workdir/openwrt/dl
          ln -sf /mnt/openwrt/tmp /workdir/openwrt/tmp        
          ln -sf /mnt/openwrt/bin /workdir/openwrt/bin
          ln -sf /mnt/openwrt/build_dir/host /workdir/openwrt/build_dir/host           
          
      - name: Multi-thread compile
        id: Multi-thread
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1)) package/luci/compile
          make -j$(($(nproc) + 1)) package/{luci-app-qbittorrent,luci-app-passwall,luci-app-shadowsocksr,luci-app-vssr,luci-app-adblock-fast,luci-app-adbyby-plus,luci-app-adguardhome,luci-app-transmission,luci-app-aria2,luci-app-bypass,luci-app-homeproxy,luci-app-kcptun,luci-app-openclash,luci-app-passwall2,luci-app-smartdns,luci-app-ssr-plus,luci-app-store,luci-app-trojan,luci-app-v2ray,luci-app-wireguard,luci-app-v2raya}/compile
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
      - name: Single-thread compile
        id: Single-thread
        if: failure() 
        run: |
          cd openwrt
          make -j1 package/luci/compile V=s
          make -j1 package/{luci-app-qbittorrent,luci-app-passwall,luci-app-shadowsocksr,luci-app-vssr,luci-app-adblock-fast,luci-app-adbyby-plus,luci-app-adguardhome,luci-app-transmission,luci-app-aria2,luci-app-bypass,luci-app-homeproxy,luci-app-kcptun,luci-app-openclash,luci-app-passwall2,luci-app-smartdns,luci-app-ssr-plus,luci-app-store,luci-app-trojan,luci-app-v2ray,luci-app-wireguard,luci-app-v2raya}/compile V=s
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
         
      - name: Move files
        run: |
          rm -rf /workdir/openwrt/dl /workdir/openwrt/tmp /workdir/openwrt/bin /workdir/openwrt/build_dir/host
          mkdir -p -m 777 /workdir/openwrt/dl /workdir/openwrt/tmp /workdir/openwrt/bin /workdir/openwrt/build_dir/host
          cp -aprf /mnt/openwrt/dl /workdir/openwrt/dl
          cp -aprf /mnt/openwrt/tmp /workdir/openwrt/tmp
          cp -aprf /mnt/openwrt/bin /workdir/openwrt/bin
          cp -aprf /mnt/openwrt/build_dir/host /workdir/openwrt/build_dir/host
          
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
             /workdir/openwrt/dl
             /workdir/openwrt/tmp/
             /workdir/openwrt/bin/
             /workdir/openwrt/build_dir/host
             /mnt/openwrt/staging_dir/
             /workdir/openwrt/feeds/
             /workdir/openwrt/build_dir/hostpkg
          key: openwrt
      
      - name: Compress directory
        run: |
          sudo rm -rf /workdir/openwrt/dl /workdir/openwrt/tmp/ /workdir/openwrt/bin/ /workdir/openwrt/build_dir/host /workdir/openwrt/feeds/ /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf staging_dir.tar.gz /workdir/openwrt/staging_dir && sudo rm -rf /workdir/openwrt/staging_dir
          bsdtar -czlf openwrt.tar.gz /workdir/openwrt && sudo rm -rf /workdir/openwrt
          bsdtar -czlf hostpkg.tar.gz /workdir/openwrt/build_dir/hostpkg && sudo rm -rf /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf host.tar.gz /mnt/openwrt/build_dir/host && sudo rm -rf /mnt/openwrt/build_dir/host
          bsdtar -czlf bin.tar.gz /mnt/openwrt/bin && sudo rm -rf /mnt/openwrt/bin
          bsdtar -czlf dl.tar.gz /mnt/openwrt/dl && sudo rm -rf /mnt/openwrt/dl
          bsdtar -czlf feeds.tar.gz /mnt/openwrt/feeds && sudo rm -rf /mnt/openwrt/feeds
          df -hT
      
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            openwrt.tar.gz
            staging_dir.tar.gz
            hostpkg.tar.gz
            host.tar.gz
            bin.tar.gz
            dl.tar.gz
            feeds.tar.gz
       
      - name: WeChat notification
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success' && !cancelled() && job.status == 'success'
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第二部分编译成功"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第二部分编译成功
       
      - name: WeChat notification
        if: failure() && !cancelled()
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第二部分编译失败"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第二部分编译失败  
         
  build2:
    needs: build1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
           
      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /var/cache/apt/archives /usr/local/share/boost /usr/local/go* /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox* google* dotnet* openjdk* mysql* php* android* mongodb* moby* snapd* libreoffice* gnome* unity-webapps-common lxd printer* cups* foomatic* hplip* bluez* aisleriot* shotwell* rhythmbox* thunderbird* transmission* totem* cheese* \
          cloud-init cloud-guest-utils cloud-initramfs-copymods cloud-initramfs-dyn-netconf ubuntu-server landscape-common linux-cloud-tools-common linux-cloud-tools-generic linux-firmware linux-tools-generic linux-modules-extra-$(uname -r) linux-headers-$(uname -r) language-pack* aspnetcore-targeting-pack*
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev libarchive-tools
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo chmod 777 /workdir
          df -hT   
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: /workdir

      - name: WeChat notification
        working-directory: /workdir
        run: |
          cd /workdir
          mkdir -p openwrt
          bsdtar -xzf openwrt.tar.gz -C /workdir/openwrt --strip-components=2 && rm openwrt.tar.gz
          ln -sf /workdir/openwrt ${{ github.workspace }}/openwrt
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt开始编译第三部分"
          rm -rf openwrt/build_dir/hostpkg openwrt/staging_dir openwrt/dl
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt开始编译第三部分
       
      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff /mnt/swapfile
          sudo rm -rf /mnt/swapfile
          sudo chmod 777 /mnt
          sudo mkdir -p -m 777 /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/build_dir/host openwrt/build_dir /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir /mnt/openwrt/build_dir /mnt/openwrt/tmp /mnt/openwrt/bin
          ln -sf /mnt/openwrt/dl openwrt/dl
          ln -sf /mnt/openwrt/tmp openwrt/tmp        
          ln -sf /mnt/openwrt/bin openwrt/bin
          # ln -sf /mnt/openwrt/build_dir/host openwrt/build_dir/host 
          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
          # ln -sf /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/hostpkg
          # ln -sf /mnt/openwrt/feeds openwrt/feeds
          ln -sf /mnt/openwrt/build_dir openwrt/build_dir
          df -hT
              
      - name: Unzip artifact
        run: |
          cd /workdir && mkdir -p openwrt/staging_dir && bsdtar -xzf staging_dir.tar.gz -C /workdir/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz 
          cd /workdir && bsdtar -xzf host.tar.gz -C /mnt/openwrt/build_dir/host --strip-components=4 && rm host.tar.gz
          cd /workdir && bsdtar -xzf bin.tar.gz -C /mnt/openwrt/bin --strip-components=3 && rm bin.tar.gz
          cd /workdir && bsdtar -xzf dl.tar.gz -C /mnt/openwrt/dl --strip-components=3 && rm dl.tar.gz
          cd /workdir && bsdtar -xzf staging_dir.tar.gz -C /mnt/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz
          cd /workdir && bsdtar -xzf feeds.tar.gz -C /mnt/openwrt/feeds --strip-components=3 && rm feeds.tar.gz
          
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
             /workdir/openwrt/dl
             /workdir/openwrt/tmp/
             /workdir/openwrt/bin/
             /workdir/openwrt/build_dir/host
             /workdir/openwrt/staging_dir/
             /workdir/openwrt/feeds/
             /workdir/openwrt/build_dir/hostpkg
          key: openwrt
          restore-keys: |
               openwrt
          
      - name: Move files
        run: |
          mv /workdir/openwrt/dl /mnt/openwrt/dl
          mv /workdir/openwrt/tmp /mnt/openwrt/tmp
          mv /workdir/openwrt/bin /mnt/openwrt/bin
          mv /workdir/openwrt/build_dir/host /mnt/openwrt/build_dir/host
          ln -sf /mnt/openwrt/dl /workdir/openwrt/dl
          ln -sf /mnt/openwrt/tmp /workdir/openwrt/tmp        
          ln -sf /mnt/openwrt/bin /workdir/openwrt/bin
          ln -sf /mnt/openwrt/build_dir/host /workdir/openwrt/build_dir/host 
          
      - name: Multi-thread compile
        id: Multi-thread
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make package/compile -j$(($(nproc) + 1))
          make package/index -j$(($(nproc) + 1))
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
      - name: Single-thread compile
        id: Single-thread
        if: failure() 
        run: |
          cd openwrt
          make -j1 package/compile V=s
          make -j1 package/index V=s
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
         
      - name: Move files
        run: |
          rm -rf /workdir/openwrt/dl /workdir/openwrt/tmp /workdir/openwrt/bin /workdir/openwrt/build_dir/host
          mkdir -p -m 777 /workdir/openwrt/dl /workdir/openwrt/tmp /workdir/openwrt/bin /workdir/openwrt/build_dir/host
          cp -aprf /mnt/openwrt/dl /workdir/openwrt/dl
          cp -aprf /mnt/openwrt/tmp /workdir/openwrt/tmp
          cp -aprf /mnt/openwrt/bin /workdir/openwrt/bin
          cp -aprf /mnt/openwrt/build_dir/host /workdir/openwrt/build_dir/host
          
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
             /workdir/openwrt/dl
             /workdir/openwrt/tmp/
             /workdir/openwrt/bin/
             /workdir/openwrt/staging_dir/
             /workdir/openwrt/build_dir/host
             /workdir/openwrt/feeds/
             /workdir/openwrt/build_dir/hostpkg
          key: openwrt
          
      - name: Compress directory
        run: |
          sudo rm -rf /workdir/openwrt/dl /workdir/openwrt/tmp/ /workdir/openwrt/bin/ /workdir/openwrt/build_dir/host /workdir/openwrt/feeds/ /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf staging_dir.tar.gz /workdir/openwrt/staging_dir && sudo rm -rf /workdir/openwrt/staging_dir
          bsdtar -czlf openwrt.tar.gz /workdir/openwrt && sudo rm -rf /workdir/openwrt
          bsdtar -czlf hostpkg.tar.gz /workdir/openwrt/build_dir/hostpkg && sudo rm -rf /workdir/openwrt/build_dir/hostpkg
          bsdtar -czlf host.tar.gz /mnt/openwrt/build_dir/host && sudo rm -rf /mnt/openwrt/build_dir/host
          bsdtar -czlf bin.tar.gz /mnt/openwrt/bin && sudo rm -rf /mnt/openwrt/bin
          bsdtar -czlf dl.tar.gz /mnt/openwrt/dl && sudo rm -rf /mnt/openwrt/dl
          bsdtar -czlf feeds.tar.gz /mnt/openwrt/feeds && sudo rm -rf /mnt/openwrt/feeds
          df -hT
      
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            openwrt.tar.gz
            staging_dir.tar.gz
            hostpkg.tar.gz
            host.tar.gz
            bin.tar.gz
            dl.tar.gz
            feeds.tar.gz
   
      - name: WeChat notification
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success' && !cancelled() && job.status == 'success'
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第三部分编译成功"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第三部分编译成功
       
      - name: WeChat notification
        if: failure() && !cancelled()
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt第三部分编译失败"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt第三部分编译失败  
         
  uploads:
    needs: build2
    runs-on: ubuntu-22.04
    steps:  
      - name: Checkout code
        uses: actions/checkout@main

      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /var/cache/apt/archives /usr/local/share/boost /usr/local/go* /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox* google* dotnet* openjdk* mysql* php* android* mongodb* moby* snapd* libreoffice* gnome* unity-webapps-common lxd printer* cups* foomatic* hplip* bluez* aisleriot* shotwell* rhythmbox* thunderbird* transmission* totem* cheese* \
          cloud-init cloud-guest-utils cloud-initramfs-copymods cloud-initramfs-dyn-netconf ubuntu-server landscape-common linux-cloud-tools-common linux-cloud-tools-generic linux-firmware linux-tools-generic linux-modules-extra-$(uname -r) linux-headers-$(uname -r) language-pack* aspnetcore-targeting-pack*
          sudo -E apt-get -qq update -y
          sudo -E apt-get -qq full-upgrade -y
          sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev libarchive-tools
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo chmod 777 /workdir
          df -hT
                             
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: /workdir

      - name: WeChat notification
        working-directory: /workdir
        run: |
          cd /workdir
          mkdir -p openwrt
          bsdtar -xzf openwrt.tar.gz -C /workdir/openwrt --strip-components=2 && rm openwrt.tar.gz
          ln -sf /workdir/openwrt ${{ github.workspace }}/openwrt
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt开始最终编译"
          rm -rf openwrt/build_dir/hostpkg openwrt/staging_dir openwrt/dl
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt开始最终编译
       
      - name: Free up disk space
        if: env.FREE_UP_DISK == 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff /mnt/swapfile
          sudo rm -rf /mnt/swapfile
          sudo chmod 777 /mnt
          sudo mkdir -p -m 777 /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/build_dir/host openwrt/build_dir /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir /mnt/openwrt/build_dir /mnt/openwrt/tmp /mnt/openwrt/bin
          ln -sf /mnt/openwrt/dl openwrt/dl
          ln -sf /mnt/openwrt/tmp openwrt/tmp        
          ln -sf /mnt/openwrt/bin openwrt/bin
          # ln -sf /mnt/openwrt/build_dir/host openwrt/build_dir/host 
          ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
          # ln -sf /mnt/openwrt/build_dir/hostpkg openwrt/build_dir/hostpkg
          # ln -sf /mnt/openwrt/feeds openwrt/feeds
          ln -sf /mnt/openwrt/build_dir openwrt/build_dir
          df -hT
               
      - name: Unzip artifact
        run: |
          cd /workdir && mkdir -p openwrt/staging_dir && bsdtar -xzf staging_dir.tar.gz -C /workdir/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz
          cd /workdir && bsdtar -xzf host.tar.gz -C /mnt/openwrt/build_dir/host --strip-components=4 && rm host.tar.gz
          cd /workdir && bsdtar -xzf bin.tar.gz -C /mnt/openwrt/bin --strip-components=3 && rm bin.tar.gz
          cd /workdir && bsdtar -xzf dl.tar.gz -C /mnt/openwrt/dl --strip-components=3 && rm dl.tar.gz
          cd /workdir && bsdtar -xzf staging_dir.tar.gz -C /mnt/openwrt/staging_dir --strip-components=3 && rm staging_dir.tar.gz
          cd /workdir && bsdtar -xzf feeds.tar.gz -C /mnt/openwrt/feeds --strip-components=3 && rm feeds.tar.gz
          
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
             /workdir/openwrt/dl
             /workdir/openwrt/tmp/
             /workdir/openwrt/bin/
             /workdir/openwrt/build_dir/host
             /workdir/openwrt/staging_dir/
             /workdir/openwrt/feeds/
             /workdir/openwrt/build_dir/hostpkg
          key: openwrt
          restore-keys: |
               openwrt
               
      - name: Move files
        run: |
          mv /workdir/openwrt/dl /mnt/openwrt/dl
          mv /workdir/openwrt/tmp /mnt/openwrt/tmp
          mv /workdir/openwrt/bin /mnt/openwrt/bin
          mv /workdir/openwrt/build_dir/host /mnt/openwrt/build_dir/host
          ln -sf /mnt/openwrt/dl /workdir/openwrt/dl
          ln -sf /mnt/openwrt/tmp /workdir/openwrt/tmp        
          ln -sf /mnt/openwrt/bin /workdir/openwrt/bin
          ln -sf /mnt/openwrt/build_dir/host /workdir/openwrt/build_dir/host  
          
      - name: Multi-thread compile
        id: Multi-thread
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1))
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
      - name: Single-thread compile
        id: Single-thread
        if: failure() 
        run: |
          cd openwrt
          make -j1 V=s
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
         
      - name: Upload packages
        uses: actions/upload-artifact@v4
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success'
        with:
          name: OpenWrt_packages${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin/packages

      - name: Upload openwrt directory
        uses: actions/upload-artifact@v4
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success'
        with:
          name: OpenWrt_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt

      - name: Organize files
        id: organize
        if: env.UPLOAD_FILES == 'true' && !cancelled()
        shell: pwsh
        run: |
          rm -rf openwrt/bin/targets
          echo "::set-output name=status::success"
          Compress-Archive -Path /workdir/openwrt/bin/packages OpenWrt_packages${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}.zip   
          Compress-Archive -Path /workdir/openwrt OpenWrt_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}.tar.gz
        
      - name: Upload files to cowtransfer
        id: cowtransfer
        if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 99 --hash --no-progress *.zip 2>&1 | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
          echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
          
      - name: Upload files to WeTransfer
        id: wetransfer
        if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress *.zip 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
 
      - name: Generate release tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
          [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
          echo "::set-output name=status::success"
   
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: |
            OpenWrt_packages${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}.zip
            OpenWrt_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}.tar.gz
            
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 5
          keep_minimum_runs: 10

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: WeChat notification - Final Result
        if: steps.Multi-thread.outputs.status == 'success' || steps.Single-thread.outputs.status == 'success' && !cancelled() && job.status == 'success'
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt编译成功"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt编译成功
       
      - name: WeChat notification - Final Failure
        if: failure() && !cancelled()
        run: |
          curl -s -o /dev/null http://www.pushplus.plus/send --data "token=${{ secrets.PUSHPLUS_TOKEN }}&content=OpenWrt编译失败"
          curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt编译失败
